'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type ColorInfo, type DnnAutocompleteCustomEvent, type DnnButtonCustomEvent, type DnnCheckboxCustomEvent, type DnnChevronCustomEvent, type DnnCollapsibleCustomEvent, type DnnColorInfo, type DnnColorInputCustomEvent, type DnnColorPickerCustomEvent, type DnnDropzoneCustomEvent, type DnnImageCropperCustomEvent, type DnnInputCustomEvent, type DnnModalCustomEvent, type DnnMonacoEditorCustomEvent, type DnnPermissionsGridCustomEvent, type DnnRichtextCustomEvent, type DnnSearchboxCustomEvent, type DnnSelectCustomEvent, type DnnSortIconCustomEvent, type DnnTextareaCustomEvent, type DnnToggleChangeEventDetail, type DnnToggleCustomEvent, type DnnTreeviewItemCustomEvent, type DnnVerticalSplitviewCustomEvent, type IPermissions, type NeedMoreItemsEventArgs } from "@dnncommunity/dnn-elements";
import type { Components } from "@dnncommunity/dnn-elements/dist/components";
import { DnnAutocomplete as DnnAutocompleteElement, defineCustomElement as defineDnnAutocomplete } from "@dnncommunity/dnn-elements/dist/components/dnn-autocomplete.js";
import { DnnButton as DnnButtonElement, defineCustomElement as defineDnnButton } from "@dnncommunity/dnn-elements/dist/components/dnn-button.js";
import { DnnCheckbox as DnnCheckboxElement, defineCustomElement as defineDnnCheckbox } from "@dnncommunity/dnn-elements/dist/components/dnn-checkbox.js";
import { DnnChevron as DnnChevronElement, defineCustomElement as defineDnnChevron } from "@dnncommunity/dnn-elements/dist/components/dnn-chevron.js";
import { DnnCollapsible as DnnCollapsibleElement, defineCustomElement as defineDnnCollapsible } from "@dnncommunity/dnn-elements/dist/components/dnn-collapsible.js";
import { DnnColorInput as DnnColorInputElement, defineCustomElement as defineDnnColorInput } from "@dnncommunity/dnn-elements/dist/components/dnn-color-input.js";
import { DnnColorPicker as DnnColorPickerElement, defineCustomElement as defineDnnColorPicker } from "@dnncommunity/dnn-elements/dist/components/dnn-color-picker.js";
import { DnnContextMenu as DnnContextMenuElement, defineCustomElement as defineDnnContextMenu } from "@dnncommunity/dnn-elements/dist/components/dnn-context-menu.js";
import { DnnDropzone as DnnDropzoneElement, defineCustomElement as defineDnnDropzone } from "@dnncommunity/dnn-elements/dist/components/dnn-dropzone.js";
import { DnnFieldset as DnnFieldsetElement, defineCustomElement as defineDnnFieldset } from "@dnncommunity/dnn-elements/dist/components/dnn-fieldset.js";
import { DnnImageCropper as DnnImageCropperElement, defineCustomElement as defineDnnImageCropper } from "@dnncommunity/dnn-elements/dist/components/dnn-image-cropper.js";
import { DnnInput as DnnInputElement, defineCustomElement as defineDnnInput } from "@dnncommunity/dnn-elements/dist/components/dnn-input.js";
import { DnnModal as DnnModalElement, defineCustomElement as defineDnnModal } from "@dnncommunity/dnn-elements/dist/components/dnn-modal.js";
import { DnnMonacoEditor as DnnMonacoEditorElement, defineCustomElement as defineDnnMonacoEditor } from "@dnncommunity/dnn-elements/dist/components/dnn-monaco-editor.js";
import { DnnPermissionsGrid as DnnPermissionsGridElement, defineCustomElement as defineDnnPermissionsGrid } from "@dnncommunity/dnn-elements/dist/components/dnn-permissions-grid.js";
import { DnnProgressBar as DnnProgressBarElement, defineCustomElement as defineDnnProgressBar } from "@dnncommunity/dnn-elements/dist/components/dnn-progress-bar.js";
import { DnnRichtext as DnnRichtextElement, defineCustomElement as defineDnnRichtext } from "@dnncommunity/dnn-elements/dist/components/dnn-richtext.js";
import { DnnSearchbox as DnnSearchboxElement, defineCustomElement as defineDnnSearchbox } from "@dnncommunity/dnn-elements/dist/components/dnn-searchbox.js";
import { DnnSelect as DnnSelectElement, defineCustomElement as defineDnnSelect } from "@dnncommunity/dnn-elements/dist/components/dnn-select.js";
import { DnnSortIcon as DnnSortIconElement, defineCustomElement as defineDnnSortIcon } from "@dnncommunity/dnn-elements/dist/components/dnn-sort-icon.js";
import { DnnTab as DnnTabElement, defineCustomElement as defineDnnTab } from "@dnncommunity/dnn-elements/dist/components/dnn-tab.js";
import { DnnTabs as DnnTabsElement, defineCustomElement as defineDnnTabs } from "@dnncommunity/dnn-elements/dist/components/dnn-tabs.js";
import { DnnTextarea as DnnTextareaElement, defineCustomElement as defineDnnTextarea } from "@dnncommunity/dnn-elements/dist/components/dnn-textarea.js";
import { DnnToggle as DnnToggleElement, defineCustomElement as defineDnnToggle } from "@dnncommunity/dnn-elements/dist/components/dnn-toggle.js";
import { DnnTreeviewItem as DnnTreeviewItemElement, defineCustomElement as defineDnnTreeviewItem } from "@dnncommunity/dnn-elements/dist/components/dnn-treeview-item.js";
import { DnnVerticalOverflowMenu as DnnVerticalOverflowMenuElement, defineCustomElement as defineDnnVerticalOverflowMenu } from "@dnncommunity/dnn-elements/dist/components/dnn-vertical-overflow-menu.js";
import { DnnVerticalSplitview as DnnVerticalSplitviewElement, defineCustomElement as defineDnnVerticalSplitview } from "@dnncommunity/dnn-elements/dist/components/dnn-vertical-splitview.js";

export type DnnAutocompleteEvents = {
    onValueChange: EventName<DnnAutocompleteCustomEvent<number | string | string[]>>,
    onValueInput: EventName<DnnAutocompleteCustomEvent<number | string | string[]>>,
    onNeedMoreItems: EventName<DnnAutocompleteCustomEvent<NeedMoreItemsEventArgs>>,
    onSearchQueryChanged: EventName<DnnAutocompleteCustomEvent<string>>,
    onItemSelected: EventName<DnnAutocompleteCustomEvent<string>>
};

export const DnnAutocomplete: StencilReactComponent<DnnAutocompleteElement, DnnAutocompleteEvents, Components.DnnAutocomplete> = /*@__PURE__*/ createComponent<DnnAutocompleteElement, DnnAutocompleteEvents, Components.DnnAutocomplete>({
    tagName: 'dnn-autocomplete',
    elementClass: DnnAutocompleteElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onValueChange: 'valueChange',
        onValueInput: 'valueInput',
        onNeedMoreItems: 'needMoreItems',
        onSearchQueryChanged: 'searchQueryChanged',
        onItemSelected: 'itemSelected'
    } as DnnAutocompleteEvents,
    defineCustomElement: defineDnnAutocomplete
});

export type DnnButtonEvents = {
    onConfirmed: EventName<DnnButtonCustomEvent<any>>,
    onCanceled: EventName<DnnButtonCustomEvent<any>>
};

export const DnnButton: StencilReactComponent<DnnButtonElement, DnnButtonEvents, Components.DnnButton> = /*@__PURE__*/ createComponent<DnnButtonElement, DnnButtonEvents, Components.DnnButton>({
    tagName: 'dnn-button',
    elementClass: DnnButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onConfirmed: 'confirmed',
        onCanceled: 'canceled'
    } as DnnButtonEvents,
    defineCustomElement: defineDnnButton
});

export type DnnCheckboxEvents = { onCheckedchange: EventName<DnnCheckboxCustomEvent<"checked" | "unchecked" | "intermediate">> };

export const DnnCheckbox: StencilReactComponent<DnnCheckboxElement, DnnCheckboxEvents, Components.DnnCheckbox> = /*@__PURE__*/ createComponent<DnnCheckboxElement, DnnCheckboxEvents, Components.DnnCheckbox>({
    tagName: 'dnn-checkbox',
    elementClass: DnnCheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCheckedchange: 'checkedchange' } as DnnCheckboxEvents,
    defineCustomElement: defineDnnCheckbox
});

export type DnnChevronEvents = { onChanged: EventName<DnnChevronCustomEvent<any>> };

export const DnnChevron: StencilReactComponent<DnnChevronElement, DnnChevronEvents, Components.DnnChevron> = /*@__PURE__*/ createComponent<DnnChevronElement, DnnChevronEvents, Components.DnnChevron>({
    tagName: 'dnn-chevron',
    elementClass: DnnChevronElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onChanged: 'changed' } as DnnChevronEvents,
    defineCustomElement: defineDnnChevron
});

export type DnnCollapsibleEvents = { onDnnCollapsibleHeightChanged: EventName<DnnCollapsibleCustomEvent<void>> };

export const DnnCollapsible: StencilReactComponent<DnnCollapsibleElement, DnnCollapsibleEvents, Components.DnnCollapsible> = /*@__PURE__*/ createComponent<DnnCollapsibleElement, DnnCollapsibleEvents, Components.DnnCollapsible>({
    tagName: 'dnn-collapsible',
    elementClass: DnnCollapsibleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDnnCollapsibleHeightChanged: 'dnnCollapsibleHeightChanged' } as DnnCollapsibleEvents,
    defineCustomElement: defineDnnCollapsible
});

export type DnnColorInputEvents = {
    onColorChange: EventName<DnnColorInputCustomEvent<DnnColorInfo>>,
    onColorInput: EventName<DnnColorInputCustomEvent<DnnColorInfo>>
};

export const DnnColorInput: StencilReactComponent<DnnColorInputElement, DnnColorInputEvents, Components.DnnColorInput> = /*@__PURE__*/ createComponent<DnnColorInputElement, DnnColorInputEvents, Components.DnnColorInput>({
    tagName: 'dnn-color-input',
    elementClass: DnnColorInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onColorChange: 'colorChange',
        onColorInput: 'colorInput'
    } as DnnColorInputEvents,
    defineCustomElement: defineDnnColorInput
});

export type DnnColorPickerEvents = { onColorChanged: EventName<DnnColorPickerCustomEvent<ColorInfo>> };

export const DnnColorPicker: StencilReactComponent<DnnColorPickerElement, DnnColorPickerEvents, Components.DnnColorPicker> = /*@__PURE__*/ createComponent<DnnColorPickerElement, DnnColorPickerEvents, Components.DnnColorPicker>({
    tagName: 'dnn-color-picker',
    elementClass: DnnColorPickerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onColorChanged: 'colorChanged' } as DnnColorPickerEvents,
    defineCustomElement: defineDnnColorPicker
});

export type DnnContextMenuEvents = NonNullable<unknown>;

export const DnnContextMenu: StencilReactComponent<DnnContextMenuElement, DnnContextMenuEvents, Components.DnnContextMenu> = /*@__PURE__*/ createComponent<DnnContextMenuElement, DnnContextMenuEvents, Components.DnnContextMenu>({
    tagName: 'dnn-context-menu',
    elementClass: DnnContextMenuElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DnnContextMenuEvents,
    defineCustomElement: defineDnnContextMenu
});

export type DnnDropzoneEvents = { onFilesSelected: EventName<DnnDropzoneCustomEvent<File[]>> };

export const DnnDropzone: StencilReactComponent<DnnDropzoneElement, DnnDropzoneEvents, Components.DnnDropzone> = /*@__PURE__*/ createComponent<DnnDropzoneElement, DnnDropzoneEvents, Components.DnnDropzone>({
    tagName: 'dnn-dropzone',
    elementClass: DnnDropzoneElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onFilesSelected: 'filesSelected' } as DnnDropzoneEvents,
    defineCustomElement: defineDnnDropzone
});

export type DnnFieldsetEvents = NonNullable<unknown>;

export const DnnFieldset: StencilReactComponent<DnnFieldsetElement, DnnFieldsetEvents, Components.DnnFieldset> = /*@__PURE__*/ createComponent<DnnFieldsetElement, DnnFieldsetEvents, Components.DnnFieldset>({
    tagName: 'dnn-fieldset',
    elementClass: DnnFieldsetElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DnnFieldsetEvents,
    defineCustomElement: defineDnnFieldset
});

export type DnnImageCropperEvents = {
    onImageCropChanged: EventName<DnnImageCropperCustomEvent<string>>,
    onImageFileCropChanged: EventName<DnnImageCropperCustomEvent<File>>
};

export const DnnImageCropper: StencilReactComponent<DnnImageCropperElement, DnnImageCropperEvents, Components.DnnImageCropper> = /*@__PURE__*/ createComponent<DnnImageCropperElement, DnnImageCropperEvents, Components.DnnImageCropper>({
    tagName: 'dnn-image-cropper',
    elementClass: DnnImageCropperElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onImageCropChanged: 'imageCropChanged',
        onImageFileCropChanged: 'imageFileCropChanged'
    } as DnnImageCropperEvents,
    defineCustomElement: defineDnnImageCropper
});

export type DnnInputEvents = {
    onValueChange: EventName<DnnInputCustomEvent<number | string | string[]>>,
    onValueInput: EventName<DnnInputCustomEvent<number | string | string[]>>
};

export const DnnInput: StencilReactComponent<DnnInputElement, DnnInputEvents, Components.DnnInput> = /*@__PURE__*/ createComponent<DnnInputElement, DnnInputEvents, Components.DnnInput>({
    tagName: 'dnn-input',
    elementClass: DnnInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onValueChange: 'valueChange',
        onValueInput: 'valueInput'
    } as DnnInputEvents,
    defineCustomElement: defineDnnInput
});

export type DnnModalEvents = { onDismissed: EventName<DnnModalCustomEvent<any>> };

export const DnnModal: StencilReactComponent<DnnModalElement, DnnModalEvents, Components.DnnModal> = /*@__PURE__*/ createComponent<DnnModalElement, DnnModalEvents, Components.DnnModal>({
    tagName: 'dnn-modal',
    elementClass: DnnModalElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onDismissed: 'dismissed' } as DnnModalEvents,
    defineCustomElement: defineDnnModal
});

export type DnnMonacoEditorEvents = { onContentChanged: EventName<DnnMonacoEditorCustomEvent<string>> };

export const DnnMonacoEditor: StencilReactComponent<DnnMonacoEditorElement, DnnMonacoEditorEvents, Components.DnnMonacoEditor> = /*@__PURE__*/ createComponent<DnnMonacoEditorElement, DnnMonacoEditorEvents, Components.DnnMonacoEditor>({
    tagName: 'dnn-monaco-editor',
    elementClass: DnnMonacoEditorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onContentChanged: 'contentChanged' } as DnnMonacoEditorEvents,
    defineCustomElement: defineDnnMonacoEditor
});

export type DnnPermissionsGridEvents = {
    onUserSearchQueryChanged: EventName<DnnPermissionsGridCustomEvent<string>>,
    onPermissionsChanged: EventName<DnnPermissionsGridCustomEvent<IPermissions>>
};

export const DnnPermissionsGrid: StencilReactComponent<DnnPermissionsGridElement, DnnPermissionsGridEvents, Components.DnnPermissionsGrid, 'permissions' | 'roleGroups' | 'roles'> = /*@__PURE__*/ createComponent<DnnPermissionsGridElement, DnnPermissionsGridEvents, Components.DnnPermissionsGrid, 'permissions' | 'roleGroups' | 'roles'>({
    tagName: 'dnn-permissions-grid',
    elementClass: DnnPermissionsGridElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onUserSearchQueryChanged: 'userSearchQueryChanged',
        onPermissionsChanged: 'permissionsChanged'
    } as DnnPermissionsGridEvents,
    defineCustomElement: defineDnnPermissionsGrid
});

export type DnnProgressBarEvents = NonNullable<unknown>;

export const DnnProgressBar: StencilReactComponent<DnnProgressBarElement, DnnProgressBarEvents, Components.DnnProgressBar> = /*@__PURE__*/ createComponent<DnnProgressBarElement, DnnProgressBarEvents, Components.DnnProgressBar>({
    tagName: 'dnn-progress-bar',
    elementClass: DnnProgressBarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DnnProgressBarEvents,
    defineCustomElement: defineDnnProgressBar
});

export type DnnRichtextEvents = {
    onValueChange: EventName<DnnRichtextCustomEvent<string>>,
    onValueInput: EventName<DnnRichtextCustomEvent<string>>
};

export const DnnRichtext: StencilReactComponent<DnnRichtextElement, DnnRichtextEvents, Components.DnnRichtext> = /*@__PURE__*/ createComponent<DnnRichtextElement, DnnRichtextEvents, Components.DnnRichtext>({
    tagName: 'dnn-richtext',
    elementClass: DnnRichtextElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onValueChange: 'valueChange',
        onValueInput: 'valueInput'
    } as DnnRichtextEvents,
    defineCustomElement: defineDnnRichtext
});

export type DnnSearchboxEvents = { onQueryChanged: EventName<DnnSearchboxCustomEvent<string>> };

export const DnnSearchbox: StencilReactComponent<DnnSearchboxElement, DnnSearchboxEvents, Components.DnnSearchbox> = /*@__PURE__*/ createComponent<DnnSearchboxElement, DnnSearchboxEvents, Components.DnnSearchbox>({
    tagName: 'dnn-searchbox',
    elementClass: DnnSearchboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onQueryChanged: 'queryChanged' } as DnnSearchboxEvents,
    defineCustomElement: defineDnnSearchbox
});

export type DnnSelectEvents = { onValueChange: EventName<DnnSelectCustomEvent<string>> };

export const DnnSelect: StencilReactComponent<DnnSelectElement, DnnSelectEvents, Components.DnnSelect> = /*@__PURE__*/ createComponent<DnnSelectElement, DnnSelectEvents, Components.DnnSelect>({
    tagName: 'dnn-select',
    elementClass: DnnSelectElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChange: 'valueChange' } as DnnSelectEvents,
    defineCustomElement: defineDnnSelect
});

export type DnnSortIconEvents = { onSortChanged: EventName<DnnSortIconCustomEvent<"asc" | "desc" | "none">> };

export const DnnSortIcon: StencilReactComponent<DnnSortIconElement, DnnSortIconEvents, Components.DnnSortIcon> = /*@__PURE__*/ createComponent<DnnSortIconElement, DnnSortIconEvents, Components.DnnSortIcon>({
    tagName: 'dnn-sort-icon',
    elementClass: DnnSortIconElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSortChanged: 'sortChanged' } as DnnSortIconEvents,
    defineCustomElement: defineDnnSortIcon
});

export type DnnTabEvents = NonNullable<unknown>;

export const DnnTab: StencilReactComponent<DnnTabElement, DnnTabEvents, Components.DnnTab, 'tabTitle'> = /*@__PURE__*/ createComponent<DnnTabElement, DnnTabEvents, Components.DnnTab, 'tabTitle'>({
    tagName: 'dnn-tab',
    elementClass: DnnTabElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DnnTabEvents,
    defineCustomElement: defineDnnTab
});

export type DnnTabsEvents = NonNullable<unknown>;

export const DnnTabs: StencilReactComponent<DnnTabsElement, DnnTabsEvents, Components.DnnTabs> = /*@__PURE__*/ createComponent<DnnTabsElement, DnnTabsEvents, Components.DnnTabs>({
    tagName: 'dnn-tabs',
    elementClass: DnnTabsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DnnTabsEvents,
    defineCustomElement: defineDnnTabs
});

export type DnnTextareaEvents = {
    onValueInput: EventName<DnnTextareaCustomEvent<string>>,
    onValueChange: EventName<DnnTextareaCustomEvent<string>>
};

export const DnnTextarea: StencilReactComponent<DnnTextareaElement, DnnTextareaEvents, Components.DnnTextarea> = /*@__PURE__*/ createComponent<DnnTextareaElement, DnnTextareaEvents, Components.DnnTextarea>({
    tagName: 'dnn-textarea',
    elementClass: DnnTextareaElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onValueInput: 'valueInput',
        onValueChange: 'valueChange'
    } as DnnTextareaEvents,
    defineCustomElement: defineDnnTextarea
});

export type DnnToggleEvents = { onCheckChanged: EventName<DnnToggleCustomEvent<DnnToggleChangeEventDetail>> };

export const DnnToggle: StencilReactComponent<DnnToggleElement, DnnToggleEvents, Components.DnnToggle> = /*@__PURE__*/ createComponent<DnnToggleElement, DnnToggleEvents, Components.DnnToggle>({
    tagName: 'dnn-toggle',
    elementClass: DnnToggleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCheckChanged: 'checkChanged' } as DnnToggleEvents,
    defineCustomElement: defineDnnToggle
});

export type DnnTreeviewItemEvents = {
    onUserExpanded: EventName<DnnTreeviewItemCustomEvent<void>>,
    onUserCollapsed: EventName<DnnTreeviewItemCustomEvent<void>>
};

export const DnnTreeviewItem: StencilReactComponent<DnnTreeviewItemElement, DnnTreeviewItemEvents, Components.DnnTreeviewItem> = /*@__PURE__*/ createComponent<DnnTreeviewItemElement, DnnTreeviewItemEvents, Components.DnnTreeviewItem>({
    tagName: 'dnn-treeview-item',
    elementClass: DnnTreeviewItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onUserExpanded: 'userExpanded',
        onUserCollapsed: 'userCollapsed'
    } as DnnTreeviewItemEvents,
    defineCustomElement: defineDnnTreeviewItem
});

export type DnnVerticalOverflowMenuEvents = NonNullable<unknown>;

export const DnnVerticalOverflowMenu: StencilReactComponent<DnnVerticalOverflowMenuElement, DnnVerticalOverflowMenuEvents, Components.DnnVerticalOverflowMenu> = /*@__PURE__*/ createComponent<DnnVerticalOverflowMenuElement, DnnVerticalOverflowMenuEvents, Components.DnnVerticalOverflowMenu>({
    tagName: 'dnn-vertical-overflow-menu',
    elementClass: DnnVerticalOverflowMenuElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as DnnVerticalOverflowMenuEvents,
    defineCustomElement: defineDnnVerticalOverflowMenu
});

export type DnnVerticalSplitviewEvents = { onWidthChanged: EventName<DnnVerticalSplitviewCustomEvent<number>> };

export const DnnVerticalSplitview: StencilReactComponent<DnnVerticalSplitviewElement, DnnVerticalSplitviewEvents, Components.DnnVerticalSplitview> = /*@__PURE__*/ createComponent<DnnVerticalSplitviewElement, DnnVerticalSplitviewEvents, Components.DnnVerticalSplitview>({
    tagName: 'dnn-vertical-splitview',
    elementClass: DnnVerticalSplitviewElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onWidthChanged: 'widthChanged' } as DnnVerticalSplitviewEvents,
    defineCustomElement: defineDnnVerticalSplitview
});
