version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: milestone
        no_empty:
          enabled: true
          message: 'A milestone must be assigned to this pull request'
      - do: label
        no_empty:
          enabled: true
          message: 'A label must be assigned to this pull request'
      - do: description
        no_empty:
          enabled: true
          message: 'A description must be provided'
