/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DnnColorPicker {}
}

declare global {


  interface HTMLDnnColorPickerElement extends Components.DnnColorPicker, HTMLStencilElement {}
  var HTMLDnnColorPickerElement: {
    prototype: HTMLDnnColorPickerElement;
    new (): HTMLDnnColorPickerElement;
  };
  interface HTMLElementTagNameMap {
    'dnn-color-picker': HTMLDnnColorPickerElement;
  }
}

declare namespace LocalJSX {
  interface DnnColorPicker extends JSXBase.HTMLAttributes<HTMLDnnColorPickerElement> {}

  interface IntrinsicElements {
    'dnn-color-picker': DnnColorPicker;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


