name: Publish_Site
on:
  push:
    branches:
      - main
      - master
      - 'release/*'

jobs:
  publish-site:
    name: publish-site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: publish-site
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run build
          npm run build-storybook
          npm run deploy-storybook -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{GITHUB_TOKEN}}