name: Publish_Site
on:
  push:
    branches:
      - main
      - master
      - 'release/*'

jobs:
  publish-site:
    name: publish-site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm install
          npm run build
          npm run build-storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: site
          folder: storybook-static # output folder from `npm run build-storybook`