name: Publish_Site
on:
  push:
    branches:
      - main
      - master
      - 'release/*'

jobs:
  publish-site:
    name: publish-site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: publish-site
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/DNNCommunity/dnn-elements.git
      - name: Run './build.sh PublishPublishSite'
        run: ./build.sh PublishSite
        env:
          GithubToken: ${{ secrets.GITHUB_TOKEN }}